name: Python CI with Coverage

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

env:
  DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uv
          make install

      - name: Run tests with coverage
        run: |
          uv run pytest \
            labels/tests.py \
            statuses/tests.py \
            tasks/tests.py \
            users/tests.py \
            --ds=task_manager.settings \
            --cov=labels \
            --cov=statuses \
            --cov=tasks \
            --cov=users \
            --cov-report=xml:coverage.xml

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.organization=eggsellentguy
            -Dsonar.projectKey=EggsellentGuy_python-project-52
            -Dsonar.coverageReportPaths=coverage.xml