name: Python Tests & Coverage

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test-and-analyze:
    runs-on: ubuntu-latest

    env:
      DJANGO_SETTINGS_MODULE: task_manager.settings
      PYTHONUNBUFFERED: 1
      SONAR_HOST_URL: https://sonarcloud.io
      SONAR_LOGIN: ${{ secrets.SONAR_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-django pytest-cov uv

      - name: Run tests and generate coverage
        run: |
          make test-coverage

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v2
        with:
          args: >
            -Dsonar.projectKey=EggsellentGuy_python-project-52
            -Dsonar.organization=eggsellentguy
            -Dsonar.python.coverage.reportPaths=coverage.xml